// Summoner Realms — "Claude's Notes".
// Developer annotations that sit beside the GPT stress-test review: for each
// point the reviewer raised, this explains whether it was a real bug (and how it
// was fixed), a misunderstanding, or expected behaviour — plus how to test it
// correctly. Rendered into the in-game "Claude's Notes" overlay (button on the
// main menu and pause menu) and mirrored in CLAUDE_NOTES.md in the repo root.
//
// Keep this in sync with CLAUDE_NOTES.md when either changes.

export const CLAUDE_NOTES_VERSION = '4.1 — Quality of Realms · 2026-07';

export function claudeNotesHTML() {
  return `
  <p class="cn-intro">Developer notes. The first section covers <b>4.1 — Quality of Realms</b>;
  after it, the previous overhaul, then the original point-by-point answers to the ChatGPT stress-test review —
  each saying whether it was a <b>real bug</b> (now fixed), a <b>misunderstanding</b>, or <b>working as intended</b>.
  Version: <code>${CLAUDE_NOTES_VERSION}</code>.</p>

  <h4>◆ 4.1 — Quality of Realms</h4>
  <p class="cn-intro">A patch pass driven by player feedback. The headline items were four bugs that
  blocked play outright, and a cave generator that read as noise.</p>
  <ul>
    <li><b class="cn-bad">Blocks could not be placed at all.</b> Real bug — fixed. Placement was gated on the
      item's <i>category</i>, but every raw material that doubles as a block (dirt, stone, wood, sand, clay,
      snow, ice, sandstone, deepstone, blightstone) is category <code>material</code> carrying a
      <code>place</code> tile. So the blocks you actually mine were the ones you could never place. It now
      gates on whether the item <i>has</i> a tile to place, which is what the placement check and the Smart
      Cursor already did.</li>
    <li><b class="cn-bad">Swords hit through solid rock.</b> Real bug — fixed. The melee hit test was a pure
      radius-and-arc check with no terrain test. Melee now needs line of sight, sampled across large targets so
      a boss leaning out of cover is still hittable. Two arcane blades (Aetheredge Greatblade, Glimmer Glaive)
      declare <code>phasing</code> and may cut through stone — a stated weapon perk rather than an oversight.</li>
    <li><b class="cn-bad">Chopping one tree stripped its neighbour's canopy.</b> Real bug — fixed. The leaf
      flood took every 8-connected leaf, so two trees whose canopies touched were a single blob. The flood is
      now bounded to the felled trunk's own canopy footprint and refuses leaves held up by a different
      standing trunk.</li>
    <li><b class="cn-bad">A falling tree reverted to an older-looking model.</b> Real bug — fixed. The topple
      animation drew the flat fallback tile sprite instead of the neighbour-aware shaded ones. Each cell's
      sprite selectors are now captured <i>before</i> the tiles are cleared, so the tree keeps its appearance
      all the way down.</li>
    <li><b class="cn-bad">Dropping items.</b> Real bug — fixed. You could drop one at a time and it flew
      straight back into your bag. You can now drop one, a chosen amount, or the whole stack, and a drop you
      threw refuses to be re-collected by you for a moment (anyone else can pick it up, so passing items in
      co-op works).</li>
    <li><b class="cn-good">Cave generation, rebuilt.</b> The old generator sampled isotropic ridged noise,
      smoothed it symmetrically, and OR-ed in fixed-radius worms — so it produced a chaotic field of bubbles,
      pinched off the links between them, and never guaranteed any of it connected. The new one is built around
      horizontally elongated domain-warped noise, depth profiles anchored to the surface line, a wide smoothing
      kernel that preserves corridors, tunnels with angular momentum and a breathing radius, chamber clusters,
      sinkhole entrances with a tapered throat, and a connectivity pass that fills isolated bubbles and links
      what remains. Measured across 40 seeds: <b>13.7% / 29.1% / 34.5%</b> open by layer, <b>1.43×</b> wider
      than tall, <b>100%</b> of underground air reachable from the surface, <b>zero</b> sealed pockets.</li>
    <li><b class="cn-good">Water.</b> A real flowing liquid layer with an active-set simulation, so a settled
      world costs nothing per frame. Pools are generated by flood-filling cave basins and surface dips; mine
      into one and it drains. You can swim, and carry it in a pail.</li>
    <li><b class="cn-good">Fishing.</b> One button casts and reels. What you pull up depends on rod tier, bait
      grade and how much open water surrounds the bobber. Bait is the new bugs, and crates open into a rolled
      loot table.</li>
    <li><b class="cn-good">Wildlife.</b> Cows, pigs, sheep, rabbits, chickens and frogs graze and bolt when you
      approach; grubs, worms, crickets, beetles, emberflies and glowmoths are caught by clicking. Glowing bugs
      are real light sources. Meat cooks at a Smeltery into food that heals and buffs.</li>
    <li><b class="cn-good">Wind.</b> New weather that blows from one side at a time on a slow seeded cadence.
      Foliage is sheared around its anchored edge so only the free end moves, phased by tile position so gusts
      visibly travel across the world. It pushes you gently on the surface and stops entirely underground.</li>
    <li><b class="cn-good">Flora.</b> Ten new plants with per-biome mixes, so crossing a seam changes the
      undergrowth as well as the ground. Corruption trees grow twisted, lurching side to side with bare
      branch stubs.</li>
    <li><b class="cn-good">Player animation and armour.</b> The character had one static pose; it now has a
      walk cycle, jump and fall poses, a swim kick and an idle breath, all derived from what it is actually
      doing. <b>Armour is finally drawn on the character</b> in each piece's own colour. Sword swings sweep
      with a tapered trail, and the arc differs by weapon class.</li>
    <li><b class="cn-good">Gravemaw, rebuilt.</b> Its head was positioned from the bounding box while the body
      came from a separate trail, so the two came apart whenever it moved. The head is now the first link of
      the chain, with fixed link lengths — plus anticipation before a leap, squash and dust on landing, and a
      jaw that snaps rather than eases.</li>
    <li><b class="cn-good">Smart Cursor.</b> It "locked onto whatever" because it scored a 9×9 neighbourhood
      around the pointer, so a tile behind you could win on distance. It now walks the ray from you to the
      cursor and takes the first useful tile — and while you hold place, it continues the run you are building,
      so dragging lays a straight gapless line.</li>
    <li><b class="cn-good">Characters.</b> Split out of worlds, Terraria-style. A summoner owns its appearance,
      inventory and achievements, and can be taken into any realm. Pre-4.1 saves migrate quietly: the newest
      world's player becomes your first character. 22 achievements.</li>
    <li><b class="cn-good">Minimap, zoom, transparent pause.</b> A three-size minimap you can drag, pinch and
      expand, working the same under touch. Zoom on <kbd>+</kbd>/<kbd>−</kbd>, Ctrl+wheel, pinch or a settings
      slider — so a boss that flies far away stays on screen. The pause menu is a translucent side panel and
      the world keeps running behind it, so you can still move and build.</li>
    <li><b class="cn-good">Hammers.</b> A per-tile shape layer with real collision: half blocks and four slope
      orientations you can genuinely walk up, plus knocking background walls off.</li>
    <li><b class="cn-good">Multiplayer.</b> The host panel gained the difficulty slider it never had — a hosted
      world used to silently inherit whatever the host was playing — plus world name and seed, a character
      preview, and a rebuilt two-card layout.</li>
    <li><b class="cn-good">Hotbar scrolling.</b> Wheel deltas are normalised to notches and accumulated, so one
      physical detent is one slot on a mouse, a trackpad or anything else. It used to collapse any delta to
      ±1, which made a trackpad flick jump fifteen slots.</li>
  </ul>
  <p class="cn-intro"><b>Testing:</b> <code>npm run check</code> (worldgen invariants + build stamps) and
  <code>npm run check:smoke</code> (boots the real game in a headless browser and drives every system through
  the actual input path — mouse position and the primary button — because every bug above lived in the
  dispatch between an input and an action).</p>

  <h4>◆ What changed in the previous overhaul</h4>
  <ul>
    <li><b class="cn-good">Terrain.</b> Rebuilt from one noise octave into seeded biome bands
      (Dunes / Verdant Reach / Frostpine Hollow / Corrupted Lands) with blended seams, a 4-octave fBm
      heightmap terraced into plateaus, layered fill down to deepstone, and caves from ridged noise
      smoothed by cellular automata with real entrance shafts. World is now 700×260.</li>
    <li><b class="cn-good">Background walls.</b> New layer behind all natural terrain. Carving a cave leaves the
      wall, and walls block daylight — which is what makes underground read as underground. The top three rows
      carry no wall, so shallow digging stays lit. <code>/debugwalls</code> shows the layer.</li>
    <li><b class="cn-good">Tile framing &amp; tree shading.</b> Every tile picks its sprite from its neighbours:
      lit top and left faces, shadowed underside, notched inner corners, grass fringing onto the dirt below it.
      Trunks are shaded as cylinders with roots and branch stubs; canopies self-shadow where enclosed.</li>
    <li><b class="cn-good">Cave background.</b> No longer switches at two fixed depths. The sky is sampled per
      screen edge from the world depth that edge is looking at and drawn as one gradient — sky, horizon, dirt,
      stone, cavern, deep — so descending is a single continuous fade.</li>
    <li><b class="cn-good">AI.</b> New <code>systems/ai.js</code>: aggro radius gated on line of sight, memory of
      your last known position, ledge and gap awareness, a local breadth-first search to route around terrain,
      separation steering, and predictive aim. Casters no longer shoot through rock; flyers no longer tunnel
      through it. <code>/debugai</code> now shows awareness state too.</li>
    <li><b class="cn-good">Bosses.</b> One state machine — reposition → telegraph → attack → recover — instead of
      independent per-attack timers. Every attack has a visible wind-up and a recovery window. Burrow and
      teleport actually hide the boss, mark where it will surface, and stop dealing contact damage from a spot
      you can't see. Flying bosses collide with terrain. Kiting one enrages it, then makes it leave.</li>
    <li><b class="cn-good">Throwables.</b> Bombs, dynamite, cling charges, ember flasks, shurikens and knives,
      all arcing under gravity and bouncing off terrain. Explosions destroy tiles and walls gated on a per-tile
      blast resistance, and damage the thrower too.</li>
    <li><b class="cn-good">Smart Cursor.</b> Picks the most useful tile in the direction you point, on PC
      (hold Ctrl) and mobile (the ◎ button). Also fixes mobile aim collapsing onto the player at rest.</li>
    <li><b class="cn-good">Inventory.</b> Slots were fighting <code>aspect-ratio</code> against
      <code>min-height</code> in a fractional grid and overflowing into the crafting panel; they are now a fixed
      size in a fixed-column grid. The DOM is built once and diffed instead of rebuilt four times a second.
      The world keeps running with the bag open and you can still move and use items.</li>
    <li><b class="cn-good">The Guide.</b> Vesper Thane spawns with the world and will explain any item you carry,
      generated from the item's own definition and cross-referenced with recipes and loot tables.</li>
    <li><b class="cn-good">Music.</b> Drop files into <code>assets/music/</code> and they play, crossfading by
      biome, depth, time of day and boss. Silent and harmless when the folder is empty.</li>
    <li><b class="cn-good">Respawn.</b> The timer is now enforced. Dying with a boss up costs 12s and ends the
      encounter, so it must be summoned again.</li>
  </ul>

  <h4>◆ Bugs found and fixed along the way</h4>
  <ul>
    <li>Enemy <code>iframes</code> were assigned on every hit and never checked.</li>
    <li>Projectiles tested collision only at their end point once per step, so fast shots
      (~15px/frame) passed through one-tile walls. Now swept.</li>
    <li>Burrowing bosses re-set <code>invuln</code> every frame — permanently invulnerable — while still
      dealing contact damage from an invisible position.</li>
    <li>The parallax cave backdrop passed a negative radius to <code>ellipse()</code> for half of all hash
      inputs (signed instead of unsigned shift).</li>
    <li>The save indicator and net status rebuilt <code>className</code> from scratch, dropping shared styling.</li>
    <li><code>respawnTimer</code> was set but never enforced; <code>mineTarget</code> was written every frame and
      never read; a duplicated <code>alive</code> guard sat in the player draw loop.</li>
    <li>Per-module <code>?build=</code> cache-busters had drifted out of sync, so a release could ship a
      half-updated module graph. One BUILD constant now stamps them all
      (<code>node tools/stamp-build.mjs</code>).</li>
  </ul>

  <h4>① Horizontal movement "didn't work"</h4>
  <ul>
    <li><b class="cn-fix">Real bug — fixed.</b> The player had <i>no auto step-up</i>, so walking into any 1-tile
      terrain bump (extremely common on natural ground) stopped horizontal movement dead while jump still worked.
      Left often looked fine (downhill) while right jammed on a ledge — exactly the "reliable one way" symptom.</li>
    <li>Fix: <code>physics.moveAndCollide</code> now auto-climbs ledges up to <code>stepHeight</code> (18px ≈ 1 tile)
      when grounded, and the player sets that height. Enemies already hopped ledges via their own AI.</li>
    <li><b>Testing note:</b> keyboard drives movement in every mode. Automated tests must give the canvas focus and
      use held keys (<code>keyboard.down('d')</code> … <code>keyboard.up('d')</code>). A/D and ←/→ both work; W/Space/↑ jump.
      In our automated run the player now moves the full ~150px/s in both directions.</li>
  </ul>

  <h4>② Mobile joystick "didn't move the player"</h4>
  <ul>
    <li><b class="cn-fix">Real bug — fixed.</b> The move joystick released itself the instant the knob was dragged past
      its own (small) bounds, because a <code>pointerout</code> handler reset it mid-drag. Pushing the stick to the edge —
      the normal way to move fast — dropped the input.</li>
    <li>Fix: the joystick uses pointer capture and now only releases on <code>pointerup</code>/<code>pointercancel</code>.</li>
    <li><b>Testing note:</b> drive it with <code>pointerdown → pointermove → pointerup</code> (or touch equivalents) on
      <code>#joyMove</code>. Keyboard also still works in mobile mode for hybrid setups.</li>
  </ul>

  <h4>③ "New/loaded world inherited an old boss / player damage"</h4>
  <ul>
    <li><b class="cn-fix">Fixed / mostly already handled.</b> New World and Load both call <code>_resetEntities()</code>,
      which clears bosses, enemies, projectiles, drops, minions and particles before the world starts. If an old boss
      survived, it was via <b>death/respawn</b>, not world creation.</li>
    <li>Now, in single-player, <b>dying despawns the boss</b> (its adds and projectiles too), and respawn clears
      combat state — so you never respawn into a boss that "shouldn't" still exist. See <code>onLocalDeath</code>.</li>
  </ul>

  <h4>④ "Black rendering / canvas corruption after placement" &amp; dark caves</h4>
  <ul>
    <li><b>Not corruption — it was the lighting model, and it was too dark.</b> Underground/enclosed tiles fell to a
      near-black floor (0.05), so caves and shaded tree undersides read as "black areas". Placing a block that roofs
      an area correctly shadows below it, which looked like "corruption" in screenshots.</li>
    <li><b class="cn-fix">Fixed:</b> the ambient light floor is raised to <b>0.14</b> and solid tiles attenuate light
      a little less, so terrain stays dimly <i>readable</i> everywhere. Torches (light 0.95) and your own glow are still
      clearly brighter, so lighting the dark still matters — you just aren't blind without it. The canvas itself is
      redrawn every frame; there is no stale/corrupt buffer.</li>
  </ul>

  <h4>⑤ Block placement gave no confirmation</h4>
  <ul>
    <li><b class="cn-fix">Fixed.</b> The aim tile now shows a <span class="cn-good">green</span> ghost of the block when
      placement is valid and a <span class="cn-bad">red</span> ghost when it isn't. A successful place shows a
      "&lt;block&gt; placed" pop; a blocked place shows the reason ("Too far away", "Needs a solid neighbour",
      "Can't place on a player", "Space is occupied").</li>
    <li><b>Rules:</b> the tile must be empty, within reach (6 tiles), touch a solid tile OR be within 3 tiles of you,
      and solid blocks can't be placed inside a player.</li>
  </ul>

  <h4>⑥ Resource gathering feedback "weak"</h4>
  <ul>
    <li><b>Working as intended (and already present).</b> Mining/chopping shows a floating "+N &lt;item&gt;" at the tile
      and the hotbar/inventory count updates immediately. Chopping a tree fells the whole trunk+canopy and pops
      "+N Wood". If a pickup didn't register, movement/targeting was the blocker (see ①) — not the pickup itself.</li>
    <li><b>Tip:</b> right-click (PC) auto-picks the correct tool for the target tile; the wrong tool still works at 25% speed.</li>
  </ul>

  <h4>⑦ Command identifiers (<code>/spawn slime</code>, <code>/give plantfiber</code>)</h4>
  <ul>
    <li><code>/spawn slime</code>: <b>already works.</b> There is no creature literally named "slime" — the slime-like foe
      is the <b>Slugling</b>. <code>slime</code>, <code>slimes</code> and <code>slug</code> are aliased to it.</li>
    <li><code>/give plantfiber</code>: <b class="cn-fix">Fixed.</b> The item id is <code>fiber</code> and its display name is
      "Plant Fiber". The resolver is now space/punctuation-insensitive, so <code>plantfiber</code>, <code>plant fiber</code>,
      <code>fiber</code> and <code>craftingbench</code> all resolve. Autocomplete (Tab) lists exact ids.</li>
    <li>Capacity message: <code>/give</code> reports "(N didn't fit)" when a stack overflows. Stacks are 99 for most
      materials (30 potions, 200 ammo). That message is the actual remaining capacity feedback.</li>
  </ul>

  <h4>⑧ <code>/killall</code> didn't clear the boss + no reset commands</h4>
  <ul>
    <li><b>By design, now clarified + expanded.</b> <code>/killall</code> only defeats regular enemies (so you can clear
      adds without ending a boss fight). It now says so when a boss is present.</li>
    <li><b class="cn-fix">New commands:</b> <code>/clearboss</code> (remove boss + adds + boss shots),
      <code>/resetcombat</code> (clear projectiles/particles/combat state), and <code>/resetworldstate</code>
      (clear all bosses + enemies + projectiles, keep terrain).</li>
  </ul>

  <h4>⑨ "Vulnerable / boss kept hitting me during debug &amp; menu transitions"</h4>
  <ul>
    <li><b class="cn-fix">Fixed for single-player.</b> Opening the Demo Commands console or the inventory now <b>freezes the
      world simulation</b> — enemies and bosses stop while you're in those panels. (A networked/shared world can't be
      frozen unilaterally, so it keeps running there.)</li>
    <li>Escape order is deliberate: it closes the console → How-to → confirm → inventory → other dialogs → then pauses.
      So Escape with the inventory open <i>closes the inventory</i>; it does not also pause. Pressing E toggles the bag.</li>
  </ul>

  <h4>⑩ Boss HP "looked full after several hits" / phases</h4>
  <ul>
    <li><b>Mostly perception — improved.</b> Bosses have large HP (600 / 1100 / 1800) and brief invulnerability windows on
      each phase change (and while burrowing), so early chip damage moves the bar slowly. Damage <i>was</i> applying
      (floating numbers confirm hits).</li>
    <li><b class="cn-fix">Added:</b> the boss bar now shows an exact <b>"HP / max (percent)"</b> readout so reduction is
      unmistakable. Phases still announce with a toast and a flash.</li>
  </ul>

  <h4>Other review notes</h4>
  <ul>
    <li><b>Menu title clipped:</b> <span class="cn-fix">fixed</span> — the title is size-capped and wraps cleanly to
      "Summoner"/"Realms" on very narrow screens instead of overflowing.</li>
    <li><b>Floating spawn:</b> <span class="cn-fix">fixed</span> — the player now spawns resting on the surface instead of
      a few tiles above it.</li>
    <li><b>Hotbar numbers "duplicated/out of order":</b> not a bug. Each slot shows its <i>select key</i> (1–9, then 0)
      in the corner and the <i>stack count</i> separately. Those are two different numbers, not duplicates.</li>
    <li><b>"Playwright button clicks didn't activate the button":</b> a test-harness/focus/timing issue, not a game bug.
      The buttons are standard <code>&lt;button onclick&gt;</code>. For automation, prefer the <code>window.__game</code> hook
      (e.g. <code>__game.startNewWorld(name, seed)</code>) or click by visible coordinates after the overlay is settled.</li>
  </ul>

  <h4>How to test quickly (for GPT)</h4>
  <ul>
    <li><code>window.__game</code> is the live game. Handy: <code>__game.startNewWorld('Name','seed')</code>,
      <code>__game.teleportBiome('underground')</code>, <code>__game.localPlayer</code>, <code>__game.bosses</code>.</li>
    <li>Useful commands: <code>/giveall</code>, <code>/give &lt;item&gt; &lt;n&gt;</code>, <code>/spawn &lt;enemy&gt; &lt;n&gt;</code>,
      <code>/spawnboss &lt;boss&gt;</code>, <code>/clearboss</code>, <code>/resetworldstate</code>, <code>/godmode</code>,
      <code>/fly</code>, <code>/time night</code>, <code>/debugcaves</code>, <code>/debugcollision</code>.</li>
    <li>Enemies: slugling, husk, boar, duneStalker, rimeWisp, bat, crawler, bonepicker, blightcrawler,
      blightshade (aliases: slime→slugling, zombie→husk, skeleton→bonepicker, spider→crawler, pig→boar).
      Bosses: grovekeeper, gravemaw, blightSovereign.</li>
    <li>New this pass: <code>/teleport dunes|frostpine</code>, <code>/debugwalls</code>,
      <code>/music &lt;context|off|status|rescan&gt;</code>, and throwables via
      <code>/give bomb|dynamite|stickyBomb|fireFlask|shuriken|throwingKnife</code>.</li>
    <li>Terrain has its own headless test: <code>npm run check:worldgen</code> asserts spawn safety, walkable
      slopes, biome contiguity, cave connectivity, wall coverage and ore banding across many seeds.</li>
  </ul>`;
}
