setblock ~ ~ ~ minecraft:air
setblock ~1 ~ ~-1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_2_0_0_south
setblock ~1 ~ ~ com_organic_forgery_and_the_harvester_kse6cimp:harvester_2_0_1_south
setblock ~1 ~ ~1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_2_0_2_south
setblock ~1 ~1 ~-1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_2_1_0_south
setblock ~1 ~1 ~ com_organic_forgery_and_the_harvester_kse6cimp:harvester_2_1_1_south
setblock ~1 ~1 ~1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_2_1_2_south
setblock ~ ~ ~-1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_1_0_0_south
setblock ~ ~ ~ com_organic_forgery_and_the_harvester_kse6cimp:harvester_1_0_1_south
setblock ~ ~ ~1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_1_0_2_south
setblock ~ ~1 ~-1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_1_1_0_south
setblock ~ ~1 ~ com_organic_forgery_and_the_harvester_kse6cimp:harvester_1_1_1_south
setblock ~ ~1 ~1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_1_1_2_south
setblock ~-1 ~ ~-1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_0_0_0_south
setblock ~-1 ~ ~ com_organic_forgery_and_the_harvester_kse6cimp:harvester_0_0_1_south
setblock ~-1 ~ ~1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_0_0_2_south
setblock ~-1 ~1 ~-1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_0_1_0_south
setblock ~-1 ~1 ~ com_organic_forgery_and_the_harvester_kse6cimp:harvester_0_1_1_south
setblock ~-1 ~1 ~1 com_organic_forgery_and_the_harvester_kse6cimp:harvester_0_1_2_south
